//! Rust binding for rpmlib: the RedHat Package Manager (RPM) library
//!
//! This crate contains idiomatic Rust bindings which aim to expose a safe
//! API to rpmlib. The low-level unsafe bindings are located in the
//! [rpmlib-sys] crate, which is automatically generated by bindgen.
//!
//! [rpmlib-sys]: https://github.com/iqlusion-io/crates/tree/master/rpmlib-sys

#![crate_name = "rpmlib"]
#![crate_type = "rlib"]
#![deny(warnings, missing_docs, trivial_casts, trivial_numeric_casts)]
#![deny(unused_import_braces, unused_qualifications)]
#![doc(html_root_url = "https://docs.rs/rpmlib/0.0.1")]

#[cfg(feature = "rpmlib-sys")]
extern crate rpmlib_sys;
