# https://github.com/RustSec/cargo-audit/blob/master/audit.toml.example

[advisories]
ignore = [
    "RUSTSEC-2023-0052", # webpki
    "RUSTSEC-2024-0336", # rustls
    "RUSTSEC-2025-0009", # ring
    "RUSTSEC-2025-0010", # ring
] # advisory IDs to ignore e.g. ["RUSTSEC-2019-0001", ...]
