name: datadog

on:
  pull_request:
    paths:
      - "datadog/**"
      - "Cargo.*"
  push:
    branches: main

defaults:
  run:
    working-directory: datadog

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        toolchain:
          - 1.56.0 # MSRV
          - stable
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          profile: minimal
      - run: cargo test --release
      - run: cargo test --release --all-features
