name: signatory

on:
  pull_request:
    paths:
      - "signatory/**"
      - "Cargo.*"
  push:
    branches: main

defaults:
  run:
    working-directory: signatory

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"
jobs:
  test:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        toolchain:
          - 1.51.0 # MSRV
          - stable
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          profile: minimal
      - run: cargo test --release --no-default-features
      - run: cargo test --release
      - run: cargo test --release --features ecdsa
      - run: cargo test --release --features ed25519
      - run: cargo test --release --features nistp256
      - run: cargo test --release --features secp256k1
      - run: cargo test --release --all-features
